# Generated by Django 5.1.2 on 2025-08-17 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+1234567890' or '123-456-7890'", regex='^\\+?\\d{3}[-.\\s]?\\d{3}[-.\\s]?\\d{4}$')]),
        ),
    ]
